"""update_user_model

Revision ID: 0677a90b38e4
Revises: ba6065aedbd6
Create Date: 2025-08-14 10:06:04.256822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0677a90b38e4'
down_revision: Union[str, Sequence[str], None] = 'ba6065aedbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_emails', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_emails', 'created_at')
    # ### end Alembic commands ###
