"""update_model_category

Revision ID: 3e14b364d80e
Revises: ce01007d2586
Create Date: 2025-08-18 14:04:43.768705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e14b364d80e'
down_revision: Union[str, Sequence[str], None] = 'ce01007d2586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_subsubcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['product_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_subsubcategories_name'), 'product_subsubcategories', ['name'], unique=False)
    op.drop_index(op.f('ix_product_sub_subcategories_id'), table_name='product_sub_subcategories')
    op.drop_table('product_sub_subcategories')
    op.add_column('product_categories', sa.Column('name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.drop_column('product_categories', 'category_name')
    op.add_column('product_subcategories', sa.Column('name', sa.String(), nullable=True))
    op.add_column('product_subcategories', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_product_subcategories_id'), table_name='product_subcategories')
    op.create_index(op.f('ix_product_subcategories_name'), 'product_subcategories', ['name'], unique=False)
    op.drop_constraint(op.f('product_subcategories_product_category_id_fkey'), 'product_subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'product_subcategories', 'product_categories', ['category_id'], ['id'])
    op.drop_column('product_subcategories', 'subcategory_name')
    op.drop_column('product_subcategories', 'product_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_subcategories', sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_subcategories', sa.Column('subcategory_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('product_subcategories_product_category_id_fkey'), 'product_subcategories', 'product_categories', ['product_category_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_subcategories_name'), table_name='product_subcategories')
    op.create_index(op.f('ix_product_subcategories_id'), 'product_subcategories', ['id'], unique=False)
    op.drop_column('product_subcategories', 'category_id')
    op.drop_column('product_subcategories', 'name')
    op.add_column('product_categories', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.drop_column('product_categories', 'name')
    op.create_table('product_sub_subcategories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sub_subcategory_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_subcategory_id'], ['product_subcategories.id'], name=op.f('product_sub_subcategories_product_subcategory_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_sub_subcategories_pkey'))
    )
    op.create_index(op.f('ix_product_sub_subcategories_id'), 'product_sub_subcategories', ['id'], unique=False)
    op.drop_index(op.f('ix_product_subsubcategories_name'), table_name='product_subsubcategories')
    op.drop_table('product_subsubcategories')
    # ### end Alembic commands ###
