"""create_related_product

Revision ID: 4f0066da875c
Revises: 041044e1a414
Create Date: 2025-08-29 17:06:30.877962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0066da875c'
down_revision: Union[str, Sequence[str], None] = '041044e1a414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id_1', sa.Integer(), nullable=False),
    sa.Column('product_id_2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('product_id_1 != product_id_2', name='ck_different_products'),
    sa.ForeignKeyConstraint(['product_id_1'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id_2'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id_1', 'product_id_2', name='uq_related_products')
    )
    op.create_index(op.f('ix_related_products_id'), 'related_products', ['id'], unique=False)
    op.create_index('ix_related_products_product_ids', 'related_products', ['product_id_1', 'product_id_2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_related_products_product_ids', table_name='related_products')
    op.drop_index(op.f('ix_related_products_id'), table_name='related_products')
    op.drop_table('related_products')
    # ### end Alembic commands ###
