"""update_user_email_model

Revision ID: 6a1e0c938732
Revises: 57c42a64eb02
Create Date: 2025-08-14 15:02:08.554169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1e0c938732'
down_revision: Union[str, Sequence[str], None] = '57c42a64eb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_emails_code', 'user_emails', ['code'], unique=False)
    op.create_unique_constraint('uq_user_emails_email', 'user_emails', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_emails_email', 'user_emails', type_='unique')
    op.drop_index('ix_user_emails_code', table_name='user_emails')
    # ### end Alembic commands ###
