"""update_user_model

Revision ID: ba6065aedbd6
Revises: c88fd790c2b6
Create Date: 2025-08-14 10:05:28.606980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6065aedbd6'
down_revision: Union[str, Sequence[str], None] = 'c88fd790c2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_emails', ['user_email_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_email_id')
    # ### end Alembic commands ###
