"""update_model_category

Revision ID: c1c372f85779
Revises: 3e14b364d80e
Create Date: 2025-08-18 16:29:44.306946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c372f85779'
down_revision: Union[str, Sequence[str], None] = '3e14b364d80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('category_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_category_name'), 'product_categories', ['category_name'], unique=True)
    op.drop_column('product_categories', 'name')
    op.add_column('product_subcategories', sa.Column('subcategory_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_product_subcategories_name'), table_name='product_subcategories')
    op.create_index(op.f('ix_product_subcategories_subcategory_name'), 'product_subcategories', ['subcategory_name'], unique=False)
    op.drop_column('product_subcategories', 'name')
    op.add_column('product_subsubcategories', sa.Column('sub_subcategory_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_product_subsubcategories_name'), table_name='product_subsubcategories')
    op.create_index(op.f('ix_product_subsubcategories_sub_subcategory_name'), 'product_subsubcategories', ['sub_subcategory_name'], unique=False)
    op.drop_column('product_subsubcategories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_subsubcategories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_subsubcategories_sub_subcategory_name'), table_name='product_subsubcategories')
    op.create_index(op.f('ix_product_subsubcategories_name'), 'product_subsubcategories', ['name'], unique=False)
    op.drop_column('product_subsubcategories', 'sub_subcategory_name')
    op.add_column('product_subcategories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_subcategories_subcategory_name'), table_name='product_subcategories')
    op.create_index(op.f('ix_product_subcategories_name'), 'product_subcategories', ['name'], unique=False)
    op.drop_column('product_subcategories', 'subcategory_name')
    op.add_column('product_categories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_categories_category_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.drop_column('product_categories', 'category_name')
    # ### end Alembic commands ###
